namespace AppModels.Enums
{
    public enum FramingTypes
    {
        RafterJoist,
        FloorJoist,
        CeilingJoist,
        DeckJoist,
        Purlin,
        RafterOutTrigger,
        OutTrigger,
        BoundaryJoist,
        Fascia,
        Trimmer,
        Rimboard,
        RafterBeam,
        RidgeBeam,
        HipRafter,
        TrussBeam,
        FloorBeam,
        LintelBeam,
        PolePlate,
        Blocking,
        Hanger,
        TieDown,
        SteelBeam,
        DeckRoofBeam,
        DeckBeam
    }
}